### ISSUE TITLE
Display does not update the current part when dumping

### ISSUE THREAD

**Issue by 16BitWonder** [DarkMatterCore/gcdumptool#17]
I noticed when dumping split xcis that the display is not updating which part it's dumping to, it will always say it's dumping to <title_name>.xc0 without incrementing to. xc1 or higher.

https://i.imgur.com/AQ45Q9O.jpg
https://i.imgur.com/7qEMc8g.jpg

**Comment by DarkMatterCore** [comment]
@16BitWonder Thanks for reporting this. Obviously an overlook on my behalf.

I'll take care of it ASAP.

**Comment by DarkMatterCore** [comment]
Fixed in aab7e24778264c46e5ffcb0c9a5deca275f28251.
