### ISSUE TITLE
nswdb.com XML database download/update

### ISSUE THREAD

**Issue by x7l7j8cc** [DarkMatterCore/gcdumptool#2]
you will add in the next release the auto update xml from nswdb.com and an auto update for the dumper itself?

**Comment by DarkMatterCore** [comment]
Yes, I will. I'm trying to get the network code to work.

An update feature for the dumper itself will probably require some additional work (HTTPS), but I guess it can be done as well.

**Comment by x7l7j8cc** [comment]
dont know, but can you use some of the https://github.com/LiquidFenrir/MultiUpdater of the 3DS? i think you can use much of this code.

**Comment by DarkMatterCore** [comment]
I suppose I can. Thanks.

**Comment by DarkMatterCore** [comment]
XML update has been added in commit fae387a18206477d66dd275fba006f18c00056d5.

I'll leave this feature request open because it isn't possible to make an "in-app" updater at this moment, due to limitations in switch-curl. When this matter gets solved, I'll close this issue.

**Comment by DarkMatterCore** [comment]
Fixed in d22add43bf9ab487d4faf432818a6d6fd72f733d.
