### ISSUE TITLE
Dump speeds slow down to nothing

### ISSUE THREAD

**Issue by AlexS2412** [DarkMatterCore/gcdumptool#3]
Tried with latest release with each second it loses 1mibps in speed. Went from start of 10mibps down to 0 before my dump ever completed.

**Comment by DarkMatterCore** [comment]
Have you tested it with a different SD card? In all my tests, it ramps up from 0 MiB/s to approximately 7.25 MiB/s, and once it gets there, it keeps that average speed for the whole process.

I'm using a 32 GB SanDisk micro SD card (UHC I). Formatted as FAT32.

**Comment by DarkMatterCore** [comment]
Hmm. It's really weird. Are you using exFAT or FAT32? Using my current test build (with changes unrelated to the dump code) I get the same speeds.

I just made a backup of my SD card, formatted it as exFAT and got a slight speed increase (around 8.50 MiB/s). But it is steadily keeping at that rate.

The code measures the transfer speed using a smoothing factor of 0.05. So it's actually weird it starts straight up from 10 MiB/s and goes down, the smoothing factor should keep it pretty lowered down for the first seconds.

If there is any other kind of information you can provide, I'd greatly appreciate it. Some screenshots or videos would be nice.

**Comment by AlexS2412** [comment]
If you have discord please contact me as i have been testing for the last 5
hours. My username is Alex S#8291 . It seems it is still slowly dumping and
has reached 1.33mibps and has not full stopped yet but is still slowing
down.

**Comment by DarkMatterCore** [comment]
Will do. Thanks for willing to help.

This comment will be kept as a placeholder for our findings through Discord. I'll be updating it.
